### ISSUE TITLE
Copy & paste from external source

### ISSUE THREAD

**Issue by codingbowoo** [taeguk/taeguk-vim#21]
Is there any other way to perform copy & paste from external source?
Using mouse right click does not work properly.
```Shift``` + ```Insert``` currently works though.

**Comment by taeguk** [comment]
나는 그냥
1. ```:set paste```
2. insert 모드 에서 붙여넣기
3. ```:set nopaste```
하는데 ㅋㅋㅋㅋ

**Comment by codingbowoo** [comment]
근데 무엇이 덮어씌워져서 마우스 우클릭은 안먹는걸까
I'm so curious

**Comment by taeguk** [comment]
마우스 우클릭으로 안 붙여넣어지는 건 vim 의 문제라기보다는 터미널의 문제일거야.
vim 안키고 그냥 shell prompt 상태에서 마우스 우클릭 해도 안먹히지 않아?

**Comment by codingbowoo** [comment]
그냥 shell prompt 상태에서는 돼!
vim 켜고 나서는 우클릭할경우 visual 모드로 넘어가

**Comment by taeguk** [comment]
shift 누른 상태에서 마우스 우클릭 해볼래?

**Comment by codingbowoo** [comment]
된다. Thanks a lot! 근데 왜 그러는 건지(?) 알려줄 수 있어?

**Comment by taeguk** [comment]
흠 글쌔... 난 vim 의 문제라기 보다는 터미널의 문제라고 생각드는데... 잘 모르겠네~ 뭐 일단 됐으니~ 뭐어때

**Comment by codingbowoo** [comment]
Got it!

**Comment by taeguk** [comment]
@codingbowoo  나중에 한번 ```:set mouse=``` 하고 나서, 다시 마우스 우클릭 붙여넣기 해볼래?
